config/routes.rb
Rails.application.routes.draw do

  resources :sedes

  get 'lineas/institucional'

  get 'lineas/zonasv'

  get 'lineas/energia'

  get 'lineas/agua'

  get 'lineas/reciclaje'

  get 'lineas/comprasv'

  get 'lineas/otras'

  get 'configuracion/index'

  post 'configuracion/usuarios'

  post 'configuracion/sedes'

  post 'users/sign_up'

  post 'users/cambio_p'

  post 'sedes/new'

  post 'sedes/edit'

  post 'sedes/index'

  get 'sessions/new'

  

  get 'alertas' => 'welcome#index', as: 'alertas'

  devise_for :users

  resources :users

  root 'welcome#index'

end

app/models/sede.rb
class Sede < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/configuracion_controller.rb
class ConfiguracionController < ApplicationController
 
layout 'barramenu'

  

   def index
    
   end

   def usuarios
     #@users = User.order('created_at DESC')
     #respond_to do |format|
     #format.html
     #format.xlsx {
    #response.headers['Content-Disposition'] = 'attachment; filename="usuarios.xlsx"'
    #}


   end
   def users
  end
end



  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
#end

app/controllers/lineas_controller.rb
class LineasController < ApplicationController

  layout 'barramenu'
  
  def institucional
  end

  def zonasv
  end

  def energia
  end

  def agua
  end

  def reciclaje
  end

  def comprasv
  end

  def otras
  end
end

app/controllers/sedes_controller.rb
class SedesController < ApplicationController
  before_action :set_sede, only: [:show, :edit, :update, :destroy]
layout 'barramenu'
  # GET /sedes
  # GET /sedes.json
  def index
    @sedes = Sede.all
  end

  # GET /sedes/1
  # GET /sedes/1.json
  def show
  end


  # GET /sedes/new
  def new
    @sede = Sede.new
  end

  # GET /sedes/1/edit
  def edit
  end

  # POST /sedes
  # POST /sedes.json
  def create
    @sede = Sede.new(sede_params)

    respond_to do |format|
      if @sede.save
        format.html { redirect_to @sede, notice: 'Un nuevo registro fue creado.' }
        format.json { render :show, status: :created, location: @sede }
      else
        format.html { render :new }
        format.json { render json: @sede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sedes/1
  # PATCH/PUT /sedes/1.json
  def update
    respond_to do |format|
      if @sede.update(sede_params)
        format.html { redirect_to @sede, notice: 'El registro se actualizo.' }
        format.json { render :show, status: :ok, location: @sede }
      else
        format.html { render :edit }
        format.json { render json: @sede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sedes/1
  # DELETE /sedes/1.json
  def destroy
    @sede.destroy
    respond_to do |format|
      format.html { redirect_to sedes_url, notice: 'El registro fue eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sede
      @sede = Sede.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sede_params
     params.require(:sede).permit(:sede_id, :ciudad, :departamento) #linea original 
     # params.permit(:sede_id, :ciudad, :departamento)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	layout 'barramenu'

	def sign_up
	end

	def cambio_p
	end

	def password
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  layout 'barramenu'

  def index
  end

  #def index
	#  if authenticate_user?
	#    redirect_to :controller=>'welcome', :action => 'index'
	#  else
	#    redirect_to '/users/sign_in'
	#  end
 # end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configuracion_helper.rb
module ConfiguracionHelper
end

app/helpers/lineas_helper.rb
module LineasHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/configuracion/_menuconfiguracion.html.erb
<% if user_signed_in? %>

        <div class="col-xs-relleno">
        <!-- Espacio relleno debajo menu principal -->
        </div>
        <div class="col-xs-standar">

              <div class="col-xs-blanco">
              </div>

              <div class="col-xs-conf">
                <div class="imagen_boton2">
                <%= image_tag "c.png", :alt => "Configuracion", :title => "Configuracion"%>  
                </div>      
              </div>
              <div class="col-xs-titulo">
              <h4><strong> Configuraci&oacute;n:</strong></h4>
              </div>
              
              <!-- Espacio entre el titulo y primer boton -->
              <div class="col-xs-espacio">
              </div>
                           
                <div class="col-xs-standar">
                  
                    <%= button_to 'Cambiar contraseña', users_cambio_p_path(resource_name), method: :post, :class => 'btn btn-default' %>
                </div>  
                  
                
                <div class="col-xs-standar">
                  <%= button_to 'Usuarios', configuracion_usuarios_path(:id), method: :edit, :class => 'btn btn-default'  %>
                </div>
                <div class="col-xs-standar">
                  <%= button_to 'Sedes', sedes_index_path, :class => 'btn btn-default'  %>
                </div>
                <div class="col-xs-standar">
                  <button type="button" class="btn btn-default">Bloques</button> 
                </div>
                <div class="col-xs-standar">
                  <button type="button" class="btn btn-default">Per&iacuteodos</button> 
                </div>
                <div class="col-xs-standar">
                  <button type="button" class="btn btn-default">Grupo Usuarios</button> 
                </div>
                 <button type="button" class="btn btn-default">Unidades de Medida</button> 
                </div>
        </div>

             
              <ul class="nav nav-tabs">
              </ul>

        

    
    </header>


  <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p>

  <%= yield %>


    <% end %> 

app/views/configuracion/_menusedes.html.erb
<%= render :partial => "configuracion/menuconfiguracion" %>

<div class="col-xs-contenido">

<div class="col-xs-standar">
  <div class="col-xs-menu"> <div class="titulo-menu"><strong> SEDES: </strong></div>
  </div>
  <div class="col-xs-standar">
      

        <div class="col-xs-menu">
          <%= button_to 'Crear', new_sede_path, :class => 'btn btn-default'  %> 
        </div>

        <div class="col-xs-menu1">
        </div>

        <div class="col-xs-menu">
          <strong>Filtro:</strong>
        </div>

        <div class="col-xs-menu0">
          <label class="checkbox-inline">
            <input type="checkbox" id="inlineCheckbox1" value="option1" checked="checked"> Activas
            </label>
          </br>
          <label class="checkbox-inline">
            <input type="checkbox" id="inlineCheckbox1" value="option1"> Inactivas
          </label>
        </div>

      
        <div class="col-xs-menu2">
            <select class="form-control" >
              <option value="value1" selected>Todas las Sedes</option> 
              <option value="value2">Institucional</option>
              <option value="value3">Medellin</option>
            </select>
        </div>
      


        <div class="col-xs-menu2">
        <input type="search" class="form-control" placeholder="Buscar">
        </div>

        <div class="col-xs-menu1">
        </div>

        <div class="col-xs-menu">
        <button type="button" class="btn btn-default">Descargar</button>
        </div>
  </div>
</div> <!--CIERRE SUBMENU-->


</div><!--CONTENIDO-->

app/views/configuracion/_menuusuarios.html.erb
<% if user_signed_in? %>

<%= render :partial => "configuracion/menuconfiguracion" %>

<div class="col-xs-contenido">


<div class="col-xs-standar">
<div class="col-xs-menu"> <div class="titulo-menu"><strong> USUARIOS: </strong></div>
</div>
<div class="col-xs-standar">
      

        <div class="col-xs-menu">
          <%= button_to 'Crear', new_registration_path(resource_name), :class => 'btn btn-default'  %> 
        </div>

        <div class="col-xs-menu1">
        </div>

        <div class="col-xs-menu">
          <strong>Filtro:</strong>
        </div>

        <div class="col-xs-menu0">
          <label class="checkbox-inline">
            <input type="checkbox" id="inlineCheckbox1" value="option1" checked="checked"> Activos
            </label>
          </br>
          <label class="checkbox-inline">
            <input type="checkbox" id="inlineCheckbox1" value="option1"> Inactivos
          </label>
        </div>

      
        <div class="col-xs-menu2">
            <select class="form-control" >
              <option value="value1" selected>Todos los Usuarios</option> 
              <option value="value2">Institucional</option>
              <option value="value3">Medellin</option>
            </select>
        </div>
      


        <div class="col-xs-menu2">
        <input type="search" class="form-control" placeholder="Buscar">
        </div>

        <div class="col-xs-menu1">
        </div>

        <div class="col-xs-menu">
        <%= button_to 'Descargar', users_path(format: :xlsx), :class => 'btn btn-default'  %>
        </div>

</div> <!--CIERRE SUBMENU-->
<% end %>

app/views/configuracion/index.html.erb
<%= render :partial => "configuracion/menuconfiguracion" %>

app/views/configuracion/sedes.html.erb
<%= render :partial => "configuracion/menuconfiguracion" %>

<div class="col-xs-contenido">

<div class="col-xs-standar">
<div class="col-xs-standar"> <div class="titulo-menu"><strong> SEDES: </strong></div>
</div>
<div class="col-xs-standar">
      

        <div class="col-xs-menu">
          <%= button_to 'Crear', new_user_registration_path(resource_name), :class => 'btn btn-default'  %> 
        </div>

        <div class="col-xs-menu1">
        </div>

        <div class="col-xs-menu">
          <strong>Filtro:</strong>
        </div>

        <div class="col-xs-menu0">
          <label class="checkbox-inline">
            <input type="checkbox" id="inlineCheckbox1" value="option1" checked="checked"> Activas
            </label>
          </br>
          <label class="checkbox-inline">
            <input type="checkbox" id="inlineCheckbox1" value="option1"> Inactivas
          </label>
        </div>

      
        <div class="col-xs-menu2">
            <select class="form-control" >
              <option value="value1" selected>Todas las Sedes</option> 
              <option value="value2">Institucional</option>
              <option value="value3">Medellin</option>
            </select>
        </div>
      


        <div class="col-xs-menu2">
        <input type="search" class="form-control" placeholder="Buscar">
        </div>

        <div class="col-xs-menu1">
        </div>

        <div class="col-xs-menu">
        <button type="button" class="btn btn-default">Descargar</button>
        </div>
</div>
</div> <!--CIERRE SUBMENU-->

<div class="col-xs-absolute">
<table class="table table-hover">
  <tr>

  		<td> <strong> Sede </strong></td>
  		<td> <strong> Ciudad </strong></td>
  		<td> <strong> Departamento </strong></td>
      <td> <strong> A/I </strong></td>
  		<td> </td>
      <td> </td>
  </tr>

  <tr>
  		<td>Bogotá</td>
  		<td>Bogotá D.C. </td>
  		<td>Cundinamarca </td>
      <td> Activo </td>
  </tr>

 <tr>
      <td>Pasto</td>
      <td>Pasto </td>
      <td>Nariño </td>
      <td> Activo </td>
  </tr>


</table>
</div>

</div><!--CONTENIDO-->

app/views/configuracion/usuarios.html.erb
<%= render :partial => "configuracion/menuusuarios" %>

<div class="col-xs-standar2">
<table class="table table-hover">
  <tr>

  		<td> <strong> Usuario </strong></td>
  		<td> <strong>Nombre </strong></td>
  		<td> <strong>Sede </strong></td>
      <td> <strong>Grupo </strong></td>
  		<td> <strong> Rol </strong></td>
      <td> <strong> A/I </strong></td>
  		<td> </td>
      <td> </td>
      <td> </td>
  </tr>
  <% User.all.each do |usuario| %>
  <tr>
  		<td><%= usuario.email %></td>
  		<td><%= usuario.nombres + " " + usuario.apellidos %></td>
  		<td> Institucional </td>
      <td> Coord. Infraestructura Sedes </td>
  		<td> Administrador </td>
      <td> Activo </td>
      <td><%= button_to 'Editar', edit_user_registration_path(usuario), method: :edit, :class => 'btn btn-primary btn-xs'  %> </td>
      <td><%= button_to 'Ver', edit_user_registration_path(usuario), method: :edit, :class => 'btn btn-primary btn-xs'  %> </td>
      <td><%= button_to 'Enviar email', edit_user_registration_path(usuario), method: :edit, :class => 'btn btn-primary btn-xs'  %> </td>
  </tr>

<% end %>

</table>
</div>

</div><!--CONTENIDO-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECOS - Sistema de Gesti&oacute;n Ambiental UCC</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>

		

	</header>


<!--<p class='notice'><%= notice %></p>
<p class='alert'><%= alert %></p> -->

<%= yield %>

</body>
</html>

app/views/layouts/barramenu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECOS - Sistema de Gesti&oacute;n Ambiental UCC</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>

			<% if user_signed_in? %>

					<div class="navbar navbar-ecos navbar-fixed-top" role="navigation">


								<div class="container-fluid">
									<div class="barra-menu">



					          <div class="row">
					          <div class="col-xs-20 col-md-12">




					 					  <!--Inicia Logo-->
					    				<div class="col-xs-e">
					       			<div class="imagen_boton"><%= image_tag "ucc.png", :alt => "Ecos", :title => "Ecos"%></div>
					            <!--imagen_boton-->
					    				</div><!--col-md-e-->
					            <!--Finaliza Logo-->




					               <!--Inicia decoracion-->
					              <div class="col-xs-deco">
					                <div class="imagen_boton"><%= image_tag "deco_menu.png" %>
					                </div><!--imagen-->
					              </div><!--decoracion-->


					              <!--inicia boton institucional-->
					              <div class="col-xs-i">
					                <div class="imagen_boton"><%= link_to image_tag("i.png", :alt => "Institucional", :title => "Institucional"), lineas_institucional_path %></div>
					              </div><!--col-md-i-->
					              <!--termina boton institucional-->
					    					

					              <!--inicia boton zonas verdes-->
					              <div class="col-xs-h">
					    				<div class="imagen_boton"><%= link_to image_tag("h.png", :alt => "Zonas Verdes", :title => "Zonas Verdes"), lineas_zonasv_path %></div>
												</div><!--col-md-h-->
					    					<!--termina boton zonas verdes-->

					              <!--inicia boton energia-->
					              <div class="col-xs-b">
					                <div class="imagen_boton"><%= link_to image_tag("b.png", :alt => "Energ&iacutea", :title => "Energ&iacutea"), lineas_energia_path %></div>
					    					</div><!--col-md-b-->
					    					<!--tremina boton energia-->

					              <!--inicia boton Agua-->
					              <div class="col-xs-a">
					    				<div class="imagen_boton"><%= link_to image_tag("a.png", :alt => "Agua", :title => "Agua"), lineas_agua_path %></div>
					    			</div>
					              <!--Termina boton Agua-->






					              <!--inicia boton reciclaje-->
					    					<div class="col-xs-r">
					    						<div class="imagen_boton"><%= link_to image_tag("r.png", :alt => "Reciclaje", :title => "Reciclaje"), lineas_reciclaje_path %></div>
					                </div>
					              <!--termina boton reciclaje-->


					              <!--Inicia Boton compras-->
					              <div class="col-xs-co">
					                <div class="imagen_boton"><div class="imagen_boton"><%= link_to image_tag("compras.png", :alt => "Compras Verdes", :title => "Compras Verdes"), lineas_comprasv_path %></div>
					                </div>
					              </div><!--col-md-o-->
					              <!-- Termina Boton compras-->

					              

					            
					    				
					    					
					              <!--Inicia Boton Otras actividades Ambientales-->
					              <div class="col-xs-o">
					    						<div class="imagen_boton"><%= link_to image_tag("o.png", :alt => "Otras Actividades", :title => "Otras Actividades"), lineas_otras_path %></div>
					    					</div><!--col-md-o-->
					              <!--Termina Boton Otras actividades Ambientales-->


					              <!--Inicia decoracion-->
					              <div class="col-xs-deco2">
					                <div class="imagen_boton"><%= image_tag "deco_menu.png" %>
					                </div><!--imagen-->
					              </div><!--decoracion-->




					              <!--Inicia Boton alertas-->
					              <div class="col-xs-al">
					                <div class="imagen_boton">
					                	<%= link_to image_tag("alerta.png", :alt => "Alertas", :title => "Alertas"), root_path %></div><!--imagen_boton-->
					                 <div class="alerta-kbd"><div class="texto-kbd">9</div></div>
					              </div><!--col-md-o-->
					              <!-- Termina Boton alertas-->

					              	


					              <!--Inicia Boton informe-->
					              <div class="col-xs-ci">
					                <a href="#"><div class="imagen_boton"><%= image_tag "informe.png", :alt => "Consultas e Informes", :title => "Consultas e Informes"%></div></a><!--imagen_boton-->
					              </div><!--col-md-o-->
					              <!-- Termina Boton informe-->


					              




					              <!--Inicia Boton salir-->
					               <div class="col-xs-s">
					                <div class="imagen_boton">
					                  <%= link_to image_tag("s.png", :alt => "Salir", :title => "Salir"), destroy_user_session_path, method: :delete %>
					                  </div>
					              </div><!--col-md-s-->
					              <!-- Termina Boton salir-->


					            <!--Inicia Boton configuracion-->  
					              <div class="col-xs-c">
					                <div class="imagen_boton">
					                	<%= link_to image_tag("c.png", :alt => "Configuración", :title => "Configuración"), configuracion_index_path %></div><!--imagen_boton-->
					              </div><!--col-md-c-->
					              <!--Termina Boton configuracion-->  


					             <!--Inicia decoracion-->
					              <div class="col-xs-er">
					                <div class="imagen_boton"><%= image_tag "deco_menu.png" %>
					                </div><!--imagen-->
					              </div><!--decoracion-->



					              <!--INFORMACION DEL USUARIO-->
					              <div class="col-xs-u">
					              	Bienvenido, <%= current_user.nombres %></br>
					                <%= current_user.email %>
					                
					              </div><!--col-md-u-->

					               
					          </div> <!--class="col-xs-20 col-md-12"-->
					          </div> <!--class: row-->


									</div><!--barra-menu-->
								</div>
						</div><!--navbar navbar-default navbar-fixed-top-->



					<!--BARRAS VERTICALES IZQUIERDAS-->
					<div class="programa">
					    <ul>
					      <li><a href="#" class="icono-programa1"><div class="imagen_huella"><%= image_tag "huellae.png", :alt => "Reduce tu huella ecológica", :title => "Reduce tu huella ecológica"%></div></a></li>

					      <li><a href="#" class="icono-programa2"><div class="imagen_huella"><%= image_tag "huellah.png", :alt => "Reduce tu huella hídrica", :title => "Reduce tu huella hídrica"%></div></a></li>


					      <li><a href="#" class="icono-programa3"><div class="imagen_huella"><%= image_tag "huellac.png", :alt => "Reduce tu huella de carbono", :title => "Reduce tu huella de carbono"%></div></a></li>
					    </ul>
		 		 </div>





	






	</header>


<!--<p class='notice'><%= notice %></p>
<p class='alert'><%= alert %></p> -->

<%= yield %>


	<% end %> 


</body>
</html>

app/views/lineas/_menuagua.html.erb
<% if user_signed_in? %>

        <div class="col-xs-relleno">
        <!-- Espacio relleno debajo menu principal -->
        </div>
        <div class="row">

              <div class="col-xs-blanco">
              </div>

              <div class="col-xs-agua">
                <div class="imagen_boton2">
                <%= image_tag "a.png", :alt => "Agua", :title => "Agua"%>  
                </div>      
              </div>
              <div class="col-xs-titulo">
              <h4><strong> Ahorro y uso eficiente del Agua</strong></h4>
              </div>
              
              <!-- Espacio entre el titulo y primer boton -->
              <div class="col-xs-espacio">
              </div>
              
                           
              <div class="col-xs-1">
                <button type="button" class="btn btn-default">Actualizar</button> 
              </div>
        </div>

             
              <ul class="nav nav-tabs">
              </ul>

            

    
    </header>


  <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p>

  <%= yield %>


    <% end %> 

app/views/lineas/_menucomprasv.html.erb
<% if user_signed_in? %>

        <div class="col-xs-relleno">
        <!-- Espacio relleno debajo menu principal -->
        </div>
        <div class="row">

              <div class="col-xs-blanco">
              </div>

              <div class="col-xs-comprasv">
                <div class="imagen_boton2">
                <%= image_tag "compras.png", :alt => "Compras Verdes", :title => "Compras Verdes"%>  
                </div>      
              </div>
              <div class="col-xs-titulo">
              <h4><strong> Compras Verdes</strong></h4>
              </div>
              
              <!-- Espacio entre el titulo y primer boton -->
              <div class="col-xs-espacio">
              </div>
              
                           
              <div class="col-xs-1">
                <button type="button" class="btn btn-default">Actualizar</button> 
              </div>
        </div>

             
              <ul class="nav nav-tabs">
              </ul>

            

    
    </header>


  <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p>

  <%= yield %>


    <% end %> 

app/views/lineas/agua.html.erb
<%= render :partial => "lineas/menuagua" %>

app/views/sedes/edit.html.erb
<h1>Editing Sede</h1>

<%= render 'form' %>

<%= link_to 'Show', @sede %> |
<%= link_to 'Back', sedes_path %>

app/views/sedes/index.html.erb
<% if user_signed_in? %>

<%= render :partial => "configuracion/menusedes" %>

<p id="notice"><%= notice %></p>

<div class="col-xs-standar">
 <div class="col-xs-blanco"></div>
    <table class="table table-hover">
      <thead>
        <tr>
          <td><strong>Sede</strong></td>
          <td><strong>Ciudad</strong></td>
          <td><strong>Departamento</strong></td>
          <td><strong></strong></td>
          <td><strong></strong></td>
         
        </tr>
      </thead>

      <tbody>
        <% @sedes.each do |sede| %>
          <tr>
            <td><%= sede.sede_id %></td>
            <td><%= sede.ciudad %></td>
            <td><%= sede.departamento %></td>
            <td><%= button_to 'Mostrar', sede, :class => 'btn btn-primary btn-xs'%></td>
            <td><%= button_to 'Editar', edit_sede_path(sede), method: :edit, :class => 'btn btn-primary btn-xs'%></td>
            <!--<td><%= button_to 'Eliminar', sede, method: :delete, data: { confirm: 'Desea Eliminar esta Sede?' }, :class => 'btn btn-primary btn-xs' %></td>-->
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <!--<%= link_to 'New Sede', new_sede_path %>-->

</div>

<% end %>

app/views/sedes/new.html.erb
<% if user_signed_in? %>


		<!--<h1>Crear nueva sede</h1>-->

		<%= render 'form' %>


		 <!--<%= link_to 'Volver a Sedes', sedes_path %>--> 
		<%= button_to 'Cancelar', sedes_index_path,  :class => 'btn btn-default' %>
	<end>

<% end %> 

app/views/sedes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sede:</strong>
  <%= @sede.sede_id %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @sede.ciudad %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @sede.departamento %>
</p>

<%= link_to 'Edit', edit_sede_path(@sede) %> |
<%= link_to 'Back', sedes_path %>

app/views/users/cambio_p.erb
<% if user_signed_in? %>

        <div class="col-xs-relleno">
        <!-- Espacio relleno debajo menu principal -->
        </div>
<div class="col-xs-contenido"></br></br></br>
</div>

  <div class="col-xs-contenido">
  
     <div class="col-xs-blanco">
  </div>
        <div class="row center-xs">

            <div class="col-xs-6 col-md-4">
        <h2>Cambie su contraseña</h2>
        <ul class="nav nav-tabs">
                      </ul>
                      </br>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%> 
        <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do |f| %>
          <%= devise_error_messages! %>
          <%= f.hidden_field :reset_password_token %>

          <div class="field">
            <%= f.label :password, "Nueva contraseña" %><br />
            <%= f.password_field :password, autofocus: true, autocomplete: "off", class:"form-control" %>
          </div>

          <div class="field">
            <%= f.label :password_confirmation, "Confirmar nueva contraseña" %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
          </div>
              </br>
          <div class="actions">
            <%= f.submit 'Cambiar Contraseña', class: 'btn btn-default' %>
            <!--<%= f.submit "Cambiar Contraseña" %>-->
            <%= button_to 'Cancelar', sedes_path, :class => 'btn btn-default' %>
          </div>
        <% end %>
        <% end %>

        </div>
        </div>

  </div>

app/views/users/sign_up.erb
<% if user_signed_in? %>

<div class="row center-xs">

  <div class="col-xs-3 col-md-3">
    </div>
    <div class="col-xs-6 col-md-4">

      <div class="box">

          </br>
      <h2>Creación Nuevo Usuario</h2>

      <ul class="nav nav-tabs">
              </ul>
              </br></br>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, class:"form-control" %>
        </div>

         <div class="field">
          <%= f.label :nombres %><br />
          <%= f.email_field :nombres, autofocus: true, class:"form-control" %>
        </div>

         <div class="field">
          <%= f.label :apellidos %><br />
          <%= f.email_field :apellidos, autofocus: true, class:"form-control" %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <% if @validatable %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off", class:"form-control" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class:"form-control" %>
        </div>

        <div class="actions">
          <!-- <%= f.submit "Sign up" %> -->
          <%= f.submit 'Crear', :class => 'btn btn-default' %>
          <%= button_to 'Cancelar', users_path, :class => 'btn btn-default'  %>
      <% end %>

      

      <% end %>


    </div>
</div>
</div>